# Generated by Django 5.0.6 on 2024-08-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=20)),
                ('course_trainer', models.CharField(max_length=20)),
                ('course_careers', models.EmailField(max_length=254)),
                ('course_id', models.PositiveSmallIntegerField()),
                ('course_description', models.CharField(max_length=20)),
                ('course_scores', models.PositiveSmallIntegerField()),
                ('course_duration', models.DurationField()),
                ('course_sessions', models.CharField(max_length=20)),
                ('course_students', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
