# Generated by Django 5.0.6 on 2024-06-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20)),
                ('class_teacher', models.CharField(max_length=20)),
                ('class_capacity', models.PositiveSmallIntegerField()),
                ('class_motto', models.CharField(max_length=20)),
                ('class_vision', models.CharField(max_length=10)),
                ('class_goals', models.CharField(max_length=20)),
                ('class_equipments', models.PositiveSmallIntegerField()),
                ('class_lessons', models.CharField(max_length=20)),
                ('class_enrollment', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
